name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  cached_network_image:
  carousel_slider_plus:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  readmore:
  smooth_page_indicator:
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  injectable:
  get_it:
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.5
  intl: ^0.19.0
  analyzer: 6.4.1
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  injectable_generator:
  build_runner:
  flutter_gen:
  flutter_native_splash: ^2.3.10



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/
    - assets/splash/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-.ttf

